version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: kanboard-secret
    volumes:
      - db:/var/lib/mysql
  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: "jenkins_lts"
    volumes:
      #- ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
    #restart: always
    networks:
      - default

  selenium-chrome:
      image: "selenium/standalone-chrome:117.0-chromedriver-117.0"
      container_name: "selenium-chrome"
      ports:
        - 4444:4444
        - 7900:7900
      networks:
        - default

  selenium-firefox:
      image: "selenium/standalone-firefox:latest"
      container_name: "selenium-firefox"
      ports:
        - 4445:4445
        - 7901:7901
      networks:
        - default


volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db: